const constants = {
	SET_CURRENT_USER: 'SET_CURRENT_USER',
	LOGIN_FACEBOOK_REQUEST: 'LOGIN_FACEBOOK_REQUEST',
	LOGIN_FACEBOOK_SUCCESS: 'LOGIN_FACEBOOK_SUCCESS',
	LOGIN_FACEBOOK_FAILURE: 'LOGIN_FACEBOOK_FAILURE',
	GET_FARK_REQUEST: 'GET_FARK_REQUEST',
	GET_FARK_SUCCESS: 'GET_FARK_SUCCESS',
	GET_FARK_FAILURE: 'GET_FARK_FAILURE'
}

export default constants